import './css/style.scss'
import './project/common.block/logo/logo.scss'
import './project/common.block/logo/logo_color-change.js'
import './project/common.block/input-text/input-text.scss'
import './project/common.block/dropdown/dropdown.scss'
import './project/common.block/dropdown/dropdown.js'